# Programming Assignment # 2 | ECE2112 | 2ECE-A

In [6]:
#Importing Numpy

In [7]:
import numpy as np

# PA2.1: Normalization Problem

# A. Normalization using std and mean (main).

In [17]:
#Code for the random 5x5 array
X = np.random.rand(5,5)

#Calculating for the mean and the standard deviation
mean = X.mean()
std = X.std()

#Normalization formula
Z = (X - mean) / std

#Saving the normalized array to a file
np.save('X_normalized.npy', Z)

print("Normalized array saved as 'X_normalized.npy'")

Normalized array saved as 'X_normalized.npy'


In [15]:
Z

array([[ 1.20741366,  0.30261358, -0.2433976 , -0.28498458, -1.66890284],
       [ 1.23889645, -0.38708155, -1.79076659,  0.10266608,  0.89370016],
       [ 1.33037332, -0.82990115,  0.61147083, -0.86602552,  1.30773572],
       [-0.47258999,  0.29098054,  0.79496831, -1.87404745,  1.42669566],
       [ 0.12480323,  0.30507279, -0.49813749,  0.52973352, -1.55128909]])

# B. Normalization using Minimum and Maximum values of X.

In [34]:
#Code for the random 5x5 array
X = np.random.rand(5,5)

#Minimum values for array X
X_min = X.min()

#Maximum values for array X
X_max = X.max()

#Normalization formula
#Centering formula: (X - X_min)
#Standard Deviation formula: (X_max - X_min)
X_normalized = (X - X_min) / (X_max - X_min)

#Saving the normalized array to a file
np.save('X_normalized.npy', X_normalized)

print("Normalized array saved as 'X_normalized.npy'")

Normalized array saved as 'X_normalized.npy'


In [32]:
print(X_normalized)

[[0.31485945 0.00851749 0.46749453 0.74742207 0.99959277]
 [0.51884298 0.62344147 0.60654251 0.         0.21934097]
 [0.61539373 0.72204213 0.12473159 0.99384271 0.29592538]
 [0.79280143 0.28167654 0.28219179 0.1813319  0.10367501]
 [0.54598799 0.69970308 0.82145719 0.18761498 1.        ]]


# PA2.2: Divisible by 3x3

In [26]:
#Create an array of the first 100 integers as A
A = np.arange(1, 101)

#Square the terms of A
sqr = A ** 2

#Reshape the array into a 10x10 ndarray 
sqr10x10 = sqr.reshape((10, 10))

#Find all the elements divisible by 3 using modulo
divisible_by_3 = sqr10x10[sqr10x10 % 3 == 0]

#Reshaping divisible_by_3 into a 3x11 array
div3 = divisible_by_3.reshape((3, 11))

#Save divisible_by_3 and print div3 
np.save('divisible_by_3.npy', divisible_by_3)
print("Elements that are divisible by 3 in the 10 x 10 array: ")
print(div3)

Elements that are divisible by 3 in the 10 x 10 array: 
[[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
