# Programming Assignment # 2 | ECE2112 | 2ECE-A

In [45]:
#Importing Numpy

In [17]:
import numpy as np

#PA2.1: Normalization Problem

In [39]:
#Code for the random 5x5 array
X = np.random.rand(5,5)

#Minimum values for array X
X_min = X.min()

#Maximum values for array X
X_max = X.max()

#Normalization formula
#Centering formula: (X - X_min)
#Standard Deviation formula: (X_max - X_min)
X_normalized = (X - X_min) / (X_max - X_min)

#Saving the normalized array to a file
np.save('X_normalized.npy', X_normalized)

print("Normalized array saved as 'X_normalized.npy'")

Normalized array saved as 'X_normalized.npy'


In [41]:
X

array([[0.74958636, 0.38932223, 0.96400814, 0.80756268, 0.54492384],
       [0.71262008, 0.6807799 , 0.02636313, 0.75738719, 0.53486437],
       [0.68892046, 0.43046723, 0.33204391, 0.52884407, 0.04250311],
       [0.48342613, 0.65154514, 0.51390401, 0.32844144, 0.96718694],
       [0.45582766, 0.76145576, 0.24423325, 0.07432023, 0.38459386]])

#PA2.2: Divisible by 3x3

In [74]:
#Create an array of the first 100 integers as A
A = np.arange(1, 101)

#Square the terms of A
sqr = A ** 2

#Reshape the array into a 10x10 ndarray 
sqr10x10 = sqr.reshape((10, 10))

#Find all the elements divisible by 3 using modulo
divisible_by_3 = squares_10x10[squares_10x10 % 3 == 0]

#Reshaping divisible_by_3 into a 3x11 array
div3 = divisible_by_3.reshape((3, 11))

#Save divisible_by_3 and print div3 
np.save('divisible_by_3.npy', divisible_by_3)
print("Elements that are divisible by 3 in the 10 x 10 array: ")
print(div3)

Elements that are divisible by 3 in the 10 x 10 array: 
[[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
