# Programming Assignment # 2 | ECE2112 | 2ECE-A

In [45]:
#Importing Numpy

In [6]:
import numpy as np

#PA2.1: Normalization Problem

# Normalization using std and mean.

In [25]:
#Code for the random 5x5 array
X = np.random.rand(5,5)

#Minimum values for array X
mean = X.mean()

#Maximum values for array X
std = X.std()

#Normalization formula
Z = (X - mean) / std

#Saving the normalized array to a file
np.save('X_normalized.npy', X_normalized)

print("Normalized array saved as 'X_normalized.npy'")

Normalized array saved as 'X_normalized.npy'


In [27]:
Z

array([[-1.41353807, -0.056654  , -0.24362483,  0.986627  , -0.05110174],
       [-0.28846619, -1.74440712,  0.2896437 ,  0.9145185 ,  1.43609886],
       [-1.99868638,  1.61579811,  0.59327461,  0.91076702,  0.21166658],
       [ 0.68410359, -0.61628463,  0.7156168 , -0.98609559, -0.9799544 ],
       [ 0.48559179,  1.23314855, -0.73999104, -1.47076959,  0.51271846]])

# Normalization using Minimum and Maximum values of X.

In [17]:
#Code for the random 5x5 array
X = np.random.rand(5,5)

#Minimum values for array X
X_min = X.min()

#Maximum values for array X
X_max = X.max()

#Normalization formula
#Centering formula: (X - X_min)
#Standard Deviation formula: (X_max - X_min)
X_normalized = (X - X_min) / (X_max - X_min)

#Saving the normalized array to a file
np.save('X_normalized.npy', X_normalized)

print("Normalized array saved as 'X_normalized.npy'")

Normalized array saved as 'X_normalized.npy'


In [31]:
X_normalized

array([[0.59329638, 0.17442254, 0.48680931, 0.1862925 , 0.43472472],
       [0.63452054, 0.25546443, 0.86937438, 0.65535946, 0.55354647],
       [0.70384159, 0.07064473, 0.45241963, 0.16095474, 0.64170652],
       [1.        , 0.98005629, 0.30667241, 0.1961771 , 0.63072176],
       [0.63583266, 0.31477736, 0.        , 0.91041564, 0.91554025]])

#PA2.2: Divisible by 3x3

In [74]:
#Create an array of the first 100 integers as A
A = np.arange(1, 101)

#Square the terms of A
sqr = A ** 2

#Reshape the array into a 10x10 ndarray 
sqr10x10 = sqr.reshape((10, 10))

#Find all the elements divisible by 3 using modulo
divisible_by_3 = squares_10x10[squares_10x10 % 3 == 0]

#Reshaping divisible_by_3 into a 3x11 array
div3 = divisible_by_3.reshape((3, 11))

#Save divisible_by_3 and print div3 
np.save('divisible_by_3.npy', divisible_by_3)
print("Elements that are divisible by 3 in the 10 x 10 array: ")
print(div3)

Elements that are divisible by 3 in the 10 x 10 array: 
[[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
